
import LocalizedStrings from 'react-native-localization';

let Strings = new LocalizedStrings({
 en:{
    homeNewGame: "QUICK GAME",
    homeArcade: "ARCADE",
    homeHowToPlay: "HOW TO PLAY",
    homeScores: "SCORES",
    homeSettings: "SETTINGS",
    homeQuit: "QUIT", 
    tutorial1: "The game's goal is to find the best route in the grid made by numbers ordered in descending order ...",
    tutorial2: "In this case 10 -> 9 -> 7 -> 6 -> 5 -> 3 -> 1 is the best route findable. It is decreasing and all the numbers are adjacent to each other. Diagonal is not admitted ...",
    tutorial3: "The score is the sum of the numbers in the route, in this case the score is 41 ...",
    tutorial4: "If you press a number higher than the last pressed or not adjacent to it, a new route will be started.",
    tutorialButton: "LET'S PLAY",
    scoresTotal: "Total",
    scoresWin: "Win",
    scoresLost: "Lost",
    scoresAvg: "Average time",
    scoresBest: "Best time",
    settingsMusic: "Music",
    settingsButtonEnable: "ENABLE",
    settingsButtonDisable: "DISABLE",
    reportYour: "YOUR SCORE",
    reportBest: "TO WIN",
    reportTitleWin: "You win",
    reportTitleLose: "You lose",
    reportRoute: "A good route was",
    reportButtonPlay: "PLAY AGAIN",
    reportButtonBack: "BACK TO MENU",
    arcadeLevel: "Level",
    arcadeLevelTitle: "SELECT THE LEVEL",
    firstTutorialTitle: "DO YOU WANT TO SEE A TUTORIAL BEFORE THE GAME?",
    firstTutorialText: "or just continue ..."
 },
 it: {
    homeNewGame: "PARTITA RAPIDA",
    homeArcade: "ARCADE",    
    homeHowToPlay: "COME GIOCARE",
    homeScores: "STATISTICHE",
    homeSettings: "IMPOSTAZIONI",
    homeQuit: "ESCI", 
    tutorial1: "Lo scopo del gioco è trovare il miglior percorso sulla griglia, fatto da numeri in ordine decrescente ...",
    tutorial2: "In questo caso 10 -> 9 -> 7 -> 6 -> 5 -> 3 -> 1 è il miglior percorso individuabile. E' decrescente e tutti i numeri sono adiacenti l'un l'altro. Le diagonali non sono ammesse ...",
    tutorial3: "Il punteggio è dato dalla somma dei numeri sul percorso scelto, in questo caso è 41 ...",
    tutorial4: "Se premi un numero maggiore dell'ultimo numero premuto oppure non adiacente ad esso, inizierà un nuovo percorso",
    tutorialButton: "GIOCA",
    scoresTotal: "Totali",
    scoresWin: "Vinte",
    scoresLost: "Perse",
    scoresAvg: "Tempo medio",
    scoresBest: "Miglior tempo",
    settingsMusic: "Musica",
    settingsButtonEnable: "ATTIVA",
    settingsButtonDisable: "DISATTIVA",
    reportYour: "PUNTEGGIO",
    reportBest: "PER VINCERE",
    reportTitleWin: "Hai vinto",
    reportTitleLose: "Hai perso",
    reportRoute: "Un buon percorso era",
    reportButtonPlay: "RIPROVA",
    reportButtonBack: "TORNA AL MENU",
    arcadeLevel: "Livello",
    arcadeLevelTitle: "SELEZIONA IL LIVELLO",
    firstTutorialTitle: "VUOI VEDERE UN TUTORIAL PRIMA DI COMINCIARE?",
    firstTutorialText: "oppure continua ..."
 },
 de: {
    homeNewGame: "SCHNELLES SPIEL",
    homeArcade: "ARCADE",
    homeHowToPlay: "WIE MAN SPIELT",
    homeScores: "STATISTIK",
    homeSettings: "EINSTELLUNGEN",
    homeQuit: "SCHLIESSEN", 
    tutorial1: "Das Ziel des Spiels ist es, die beste Route im Raster zu finden, die durch Zahlen in absteigender Reihenfolge erfolgt ...",
    tutorial2: "In diesem Fall ist 10 -> 9 -> 7 -> 6 -> 5 -> 3 -> 1 die beste nachweisbare Route. Es ist absteigend und alle Zahlen sind nebeneinander. Diagonalen sind nicht erlaubt ...",
    tutorial3: "Die Punktzahl ergibt sich aus der Summe der Zahlen auf der gewählten Route, in diesem Fall ist es 41 ...",
    tutorial4: "Wenn du eine Nummer drückst, die größer ist als die letzte Nummer oder einer der nicht benachbart ist, wird eine neue Route beginnen",
    tutorialButton: "SPEIL",
    scoresTotal: "Gesamt",
    scoresWin: "Gewonnen",
    scoresLost: "Verloren",
    scoresAvg: "Durchschnittliche Zeit",
    scoresBest: "Bester Zeit",
    settingsMusic: "Musik",
    settingsButtonEnable: "AKTIV",
    settingsButtonDisable: "DEAKTIV",
    reportYour: "PUNKTE",
    reportBest: "UM ZU GEWINNEN",
    reportTitleWin: "Du hast gewonnen",
    reportTitleLose: "Du hast verloren",
    reportRoute: "Eine gute Route war",
    reportButtonPlay: "VERSUCH ERNEUT",
    reportButtonBack: "ZURUCK ZUM MENU",
    arcadeLevel: "Ebene",
    arcadeLevelTitle: "WÄHLEN SIE DIE EBENE",
    firstTutorialTitle: "WOLLEN SIE EIN TUTORIAL VOR DEM SPIEL SEHEN?",
    firstTutorialText: "oder einfach weitermachen ..."

},
fr: {
    homeNewGame: "JEU RAPIDE",
    homeArcade: "ARCADE",
    homeHowToPlay: "COMMENT JOUER",
    homeScores: "STATISTIQUES",
    homeSettings: "PARAMÈTRES",
    homeQuit: "QUITTER", 
    tutorial1: "Le but du jeu c'est trouver le meilleur itinéraire sur la grille, composé de nombres en ordre décroissant  ...",
    tutorial2: "Dans ce cas 10 -> 9 -> 7 -> 6 -> 5 -> 3 -> 1 c'est le meilleur itinéraire. Il est decroissant et le chiffres sont tous près. Les diagonales ne sont pas autorisées ...",
    tutorial3: "Le score coïncide avec la somme de les chiffres dans le itinéraire choisi ...",
    tutorial4: "Si vous appuyez sur une plus grande chiffre de la dernière ou pas adjacent à elle, va commencer un nouveau itinéraire",
    tutorialButton: "JEU",
    scoresTotal: "Total",
    scoresWin: "Gagnés",
    scoresLost: "Perdus",
    scoresAvg: "Temps moyen",
    scoresBest: "Meilleur temps",
    settingsMusic: "Musique",
    settingsButtonEnable: "ACTIVE",
    settingsButtonDisable: "DÈSACTIVE",
    reportYour: "SCORE",
    reportBest: "POUR GAGNER",
    reportTitleWin: "Tu as gagné",
    reportTitleLose: "Tu as perdu",
    reportRoute: "Un bon itinérarie ça aurait été",
    reportButtonPlay: "RÈESSAYER",
    reportButtonBack: "RETOURNER AU MENU",
    arcadeLevel: "Niveau",
    arcadeLevelTitle: "SÉLECTIONNEZ LE NIVEAU",
    firstTutorialTitle: "VOULEZ-VOUS VOIR UN TUTORIAL AVANT LE JEU?",
    firstTutorialText: "ou juste continuer ..."
 },
cn: {
        homeNewGame: "快速游戏",
        homeArcade: "拱廊",
        homeHowToPlay: "游戏规则",
        homeScores: "分数",
        homeSettings: "设置",
        homeQuit: "退出", 
        tutorial1: "游戏的目标是在网格中找到最佳路径，网格中的数字是以逆序排列的......",
        tutorial2: "在这种情况下，10 -> 9 -> 7 -> 6 -> 5 -> 3 -> 1是最佳路径。数目逐渐降低，以及所有的数都是相邻的。不允许对角线…",
        tutorial3: "分数是路径上数字的和，所以在这种情况下，分数是41……",
        tutorial4: "如果你按下比上次按的数字高或不相邻的数字，就会开始一条新的路径。",
        tutorialButton: "让我们开始吧",
        scoresTotal: "总数",
        scoresWin: "胜利",
        scoresLost: "失败",
        scoresAvg: "平均时间",
        scoresBest: "最佳时间",
        settingsMusic: "音乐",
        settingsButtonEnable: "启用",
        settingsButtonDisable: "禁用",
        reportYour: "你的分数",
        reportBest: "需要获胜的",
        reportTitleWin: "你赢了",
        reportTitleLose: "你输了",
        reportRoute: "最佳路线是",
        reportButtonPlay: "再玩一次",
        reportButtonBack: "回到菜单",
        arcadeLevel: "水平",
        arcadeLevelTitle: "选择水平",
        firstTutorialTitle: "你想在比赛前看到补习",
        firstTutorialText: "或者继续"
},
pn:{
    homeNewGame: "JOGO RÁPIDO",
    homeArcade: "ARCADE",
    homeHowToPlay: "COMO JOGAR",
    homeScores: "PONTUAÇÃO",
    homeSettings: "CONFIGURAÇÕES",
    homeQuit: "SAIR", 
    tutorial1: "O objetivo do jogo é encontrar no ladrilho o melhor caminho feito pelos números, ordenados do maior para o menor...",
    tutorial2: "Nesse caso 10 -> 9 -> 7 -> 6 -> 5 -> 3 -> 1 é a melhor rota. Os números vão decrescendo e todos são próximos uns aos outros. Diagonais não são permitidas ...",
    tutorial3: "A pontuação é a soma dos números no caminho, nesse caso, a pontuação é 41 ...",
    tutorial4: "Se você tocar num número maior que o último escolhido ou que não seja próximo do anterior, uma nova rota será iniciada.",
    tutorialButton: "VAMOS JOGAR",
    scoresTotal: "Total",
    scoresWin: "Vitórias",
    scoresLost: "Derrotas",
    scoresAvg: "Tempo médio",
    scoresBest: "Melhor tempo",
    settingsMusic: "Musica",
    settingsButtonEnable: "HABILITAR",
    settingsButtonDisable: "DESABILITAR",
    reportYour: "SUA PONTUAÇÃO",
    reportBest: "PARA GANHAR",
    reportTitleWin: "Você venceu",
    reportTitleLose: "Você perdeu",
    reportRoute: "O melhor caminho era",
    reportButtonPlay: "JOGAR DE NOVO",
    reportButtonBack: "VOLTAR AO MENU",
    arcadeLevel: "Nível",
    arcadeLevelTitle: "SELECIONE O NÍVEL",
    firstTutorialTitle: "VOCÊ QUER VER UM TUTORIAL ANTES DO JOGO",
    firstTutorialText: "ou apenas continuar ..."
 },
 ru:{
    homeNewGame: "БЫСТРАЯ ИГРА",
    homeArcade: "АРКАДА",
    homeHowToPlay: "ПРАВИЛА ИГРЫ",
    homeScores: "РЕЙТИНГ",
    homeSettings: "НАСТРОЙКИ",
    homeQuit: "Выйти",
    tutorial1: "Цель игры найти наилучший маршрут, можно идти по квадратам только в порядке убывания",
    tutorial2: "Например 10 -> 9 -> 7 -> 6 -> 5 -> 3 -> 1 наилучший маршрут. Путь убывающий и мы двигаемся по соседним клеткам. Двигатся по диогонали нельзя.",
    tutorial3: "Количество очков за игру - сумма всех клеток на пути, в этом примере счет - 41.",
    tutorial4: "Если нажать на клетку с большим номером чем на предыдущей, маршрут сбросится и вы начнете новый маршрут.",
    tutorialButton: "ИГРАТЬ!",
    scoresTotal: "Всего",
    scoresWin: "Победа",
    scoresLost: "Поражение",
    scoresAvg: "Среднее время",
    scoresBest: "Лучшее время",
    settingsMusic: "Музыка",
    settingsButtonEnable: "ВКЛЮЧИТЬ",
    settingsButtonDisable: "ВЫКЛЮЧИТЬ",
    reportYour: "ВАШ СЧЕТ",
    reportBest: "ЧТОБЫ ПОБЕДИТЬ",
    reportTitleWin: "Вы победили",
    reportTitleLose: "ВЫ проиграли",
    reportRoute: "Лучший маршрут был",
    reportButtonPlay: "СЫГРАТЬ СНОВА",
    reportButtonBack: "НАЗАД В МЕНЮ",
    arcadeLevel: "уровень",
    arcadeLevelTitle: "ВЫБЕРИТЕ УРОВЕНЬ",
    firstTutorialTitle: "ВЫ ХОТИТЕ УВИДЕТЬ ОБРАЗОВАНИЕ ДО ИГРЫ",
    firstTutorialText: "или просто продолжить ..."
  }
});

module.exports = Strings;