# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runtics' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Runtics
  pod 'Google-Mobile-Ads-SDK'

  target 'Runtics-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RunticsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
